import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowDownCircle, ArrowUpCircle, MoreHorizontal } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { formatCurrency, formatDate } from "@/lib/utils";
export function TransactionCard({ transaction, onEdit, onDelete }) {
    const isCashIn = transaction.type === "CASH_IN";
    const Icon = isCashIn ? ArrowDownCircle : ArrowUpCircle;
    return (_jsxs(Card, { className: "flex items-start justify-between gap-3 rounded-2xl p-4", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "rounded-xl bg-surface p-2", children: _jsx(Icon, { className: `h-4 w-4 ${isCashIn ? "text-success" : "text-danger"}`, "aria-hidden": true }) }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("p", { className: "text-sm font-medium text-text", children: transaction.reason || transaction.category }), _jsx("span", { className: "rounded-full border border-border px-2 py-0.5 text-[10px] uppercase tracking-[0.2em] text-text-muted", children: transaction.category })] }), _jsx("p", { className: "mt-1 text-xs text-text-muted", children: transaction.note || "No note provided" }), _jsx("p", { className: "mt-1 text-[11px] text-text-muted", children: formatDate(transaction.occurredAt) })] })] }), _jsxs("div", { className: "text-right", children: [_jsx("p", { className: `text-sm font-semibold ${isCashIn ? "text-success" : "text-danger"}`, children: formatCurrency(transaction.amount) }), _jsxs("div", { className: "mt-2 flex items-center gap-1 text-[11px] text-text-muted", children: [onEdit && (_jsx("button", { type: "button", className: "rounded-lg p-1 hover:bg-white/5", onClick: () => onEdit(transaction), "aria-label": "Edit transaction", children: _jsx(MoreHorizontal, { className: "h-3 w-3", "aria-hidden": true }) })), onDelete && (_jsx("button", { type: "button", className: "rounded-lg p-1 hover:bg-white/5", onClick: () => onDelete(transaction), "aria-label": "Delete transaction", children: _jsx(MoreHorizontal, { className: "h-3 w-3", "aria-hidden": true }) }))] })] })] }));
}
